"""add_tenants_and_tenant_id_to_users

Revision ID: 06be19dbc154
Revises: deba7447dfd5
Create Date: 2026-03-02 14:03:26.404288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06be19dbc154'
down_revision: Union[str, None] = 'deba7447dfd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='tenant_plan_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.drop_index('idx_intent_keywords_intent', table_name='intent_keywords', postgresql_where='(enabled = true)')
    op.drop_index('uq_intent_keyword', table_name='intent_keywords')
    op.drop_table('intent_keywords')
    op.drop_index('idx_actions_issue', table_name='actions')
    op.drop_column('conversations', 'content')
    op.alter_column('decisions', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('decisions_issue_id_fkey', 'decisions', type_='foreignkey')
    op.drop_column('decisions', 'after_value')
    op.drop_column('decisions', 'before_value')
    op.drop_column('decisions', 'issue_id')
    op.drop_column('decisions', 'change_type')
    op.add_column('projects', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('projects', sa.Column('slug', sa.String(length=63), nullable=True))
    op.add_column('projects', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('users', sa.Column('invited_by', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'invited_by')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_column('projects', 'archived_at')
    op.drop_column('projects', 'slug')
    op.drop_column('projects', 'tenant_id')
    op.add_column('decisions', sa.Column('change_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('decisions', sa.Column('issue_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('decisions', sa.Column('before_value', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('decisions', sa.Column('after_value', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('decisions_issue_id_fkey', 'decisions', 'issues', ['issue_id'], ['id'])
    op.alter_column('decisions', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('conversations', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_actions_issue', 'actions', ['issue_id'], unique=False)
    op.create_table('intent_keywords',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('keyword', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('match_type', sa.VARCHAR(length=10), server_default=sa.text("'partial'::character varying"), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='intent_keywords_pkey')
    )
    op.create_index('uq_intent_keyword', 'intent_keywords', ['intent', 'keyword'], unique=True)
    op.create_index('idx_intent_keywords_intent', 'intent_keywords', ['intent'], unique=False, postgresql_where='(enabled = true)')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
