"""add_tenant_id_to_items_actions

Revision ID: 19cfd954b5cc
Revises: 81e8800d8d52
Create Date: 2026-03-02 15:45:33.729798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cfd954b5cc'
down_revision: Union[str, None] = '81e8800d8d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('items',   sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index('ix_items_tenant_id',   'items',   ['tenant_id'])
    op.create_foreign_key(None, 'items',   'tenants', ['tenant_id'], ['id'])
    op.add_column('actions', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index('ix_actions_tenant_id', 'actions', ['tenant_id'])
    op.create_foreign_key(None, 'actions', 'tenants', ['tenant_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
