"""add_invite_tokens

Revision ID: 1fee9816c350
Revises: 06be19dbc154
Create Date: 2026-03-02 14:56:35.457862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fee9816c350'
down_revision: Union[str, None] = '06be19dbc154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_invite_tokens_tenant_id'), 'invite_tokens', ['tenant_id'], unique=False)
    op.drop_constraint('actions_tenant_id_fkey', 'actions', type_='foreignkey')
    op.drop_column('actions', 'tenant_id')
    op.drop_constraint('conversations_tenant_id_fkey', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'tenant_id')
    op.drop_constraint('decisions_tenant_id_fkey', 'decisions', type_='foreignkey')
    op.drop_column('decisions', 'tenant_id')
    op.drop_constraint('inputs_tenant_id_fkey', 'inputs', type_='foreignkey')
    op.drop_column('inputs', 'tenant_id')
    op.drop_constraint('issues_tenant_id_fkey', 'issues', type_='foreignkey')
    op.drop_column('issues', 'tenant_id')
    op.drop_constraint('items_tenant_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('items_tenant_id_fkey', 'items', 'tenants', ['tenant_id'], ['id'])
    op.add_column('issues', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('issues_tenant_id_fkey', 'issues', 'tenants', ['tenant_id'], ['id'])
    op.add_column('inputs', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('inputs_tenant_id_fkey', 'inputs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('decisions', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('decisions_tenant_id_fkey', 'decisions', 'tenants', ['tenant_id'], ['id'])
    op.add_column('conversations', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('conversations_tenant_id_fkey', 'conversations', 'tenants', ['tenant_id'], ['id'])
    op.add_column('actions', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('actions_tenant_id_fkey', 'actions', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_invite_tokens_tenant_id'), table_name='invite_tokens')
    op.drop_table('invite_tokens')
    # ### end Alembic commands ###
