"""add_tenant_id_to_inputs

Revision ID: 81e8800d8d52
Revises: b10866687a0f
Create Date: 2026-03-02 15:43:25.036559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e8800d8d52'
down_revision: Union[str, None] = 'b10866687a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_inputs_tenant_id'), 'inputs', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'inputs', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inputs', type_='foreignkey')
    op.drop_index(op.f('ix_inputs_tenant_id'), table_name='inputs')
    op.drop_column('inputs', 'tenant_id')
    # ### end Alembic commands ###
