"""sync_tenant_id_models

Revision ID: b10866687a0f
Revises: 1fee9816c350
Create Date: 2026-03-02 15:04:23.800857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10866687a0f'
down_revision: Union[str, None] = '1fee9816c350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'tenants', ['tenant_id'], ['id'])
    op.add_column('issues', sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_issues_tenant_id'), 'issues', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'issues', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_index(op.f('ix_issues_tenant_id'), table_name='issues')
    op.drop_column('issues', 'tenant_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_column('conversations', 'tenant_id')
    # ### end Alembic commands ###
